---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(readxl)
library(ggplot2)
library(plotly)
```

```{r}
f <- file.choose()

boost <- read_xlsx(f)
```


```{r}
boost_dens <- density(boost$Boost)
plot(boost_dens)



```


```{r}
ggplotly(ggplot(boost, aes(x = Boost)) + geom_density())
```




```{r}
bxy <- data.frame(bx = boost_dens$x, by = boost_dens$y)

plot(bxy)

```
```{r}
shapiro.test(boost$Boost)
```

```{r}
CI_z <- function (x, ci = 0.95)
{
standard_deviation <- sd(x)
sample_size <- length(x)
Margin_Error <- abs(qnorm((1-ci)/2))* standard_deviation/sqrt(sample_size)
df_out <- data.frame( sample_size=length(x), Mean=mean(x), sd=sd(x),
Margin_Error=Margin_Error,
'CI lower limit'=(mean(x) - Margin_Error),
'CI Upper limit'=(mean(x) + Margin_Error)) %>%
tidyr::pivot_longer(names_to = "Measurements", values_to ="values", 1:6 )
return(df_out)
}


CI_t <- function (x, ci = 0.95)
{
Margin_Error <- qt(ci + (1 - ci)/2, df = length(x) - 1) * sd(x)/sqrt(length(x))
df_out <- data.frame( sample_size=length(x), Mean=mean(x), sd=sd(x),
Margin_Error=Margin_Error,
'CI lower limit'=(mean(x) - Margin_Error),
'CI Upper limit'=(mean(x) + Margin_Error)) %>%
tidyr::pivot_longer(names_to = "Measurements", values_to ="values", 1:6 )
return(df_out)
}
```

```{r}
CI_t(boost$Boost, 0.95)
```
```{r}
t.test(boost$Boost)
```

